CREATE TABLE CATEGORY(
    ID INT AUTO_INCREMENT,
	NAME VARCHAR(255)
);

INSERT INTO CATEGORY ( ID, NAME )
VALUES 
(1, 'Shirt' ), 
(2, 'Pant'  ), 
(3, 'Caps'  );
(4, 'Socks' );


CREATE TABLE PRODUCT(
    ID INT AUTO_INCREMENT,
	BRAND_NAME VARCHAR(255),
    COLOR VARCHAR(255),
    SIZE VARCHAR(255),
	PRICE INT,
    SKU INT,
    AVAIL_QTY INT,
	CATEGORY_ID INT
);

INSERT INTO PRODUCT ( ID, BRAND_NAME, COLOR, SIZE, PRICE, SKU, AVAIL_QTY, CATEGORY_ID )
VALUES 
(1, 'Lewis', 'RED', '36', 1540, 5, 23, 1), 
(2, 'Roadster', 'BULE',	'M', 490, 4,	10, 3), 
(3, 'Lee', 'RED', 'L', 999, 10, 2, 2);
(4, 'Otto', 'YELLOW', '41', 555, 5, 8,1);
(5, 'Lewis', 'RED', 'M', 1540, 5, 8,1);