DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS PRODUCT;
 
CREATE TABLE CATEGORY(
    ID INT AUTO_INCREMENT,
	NAME VARCHAR(255)
);


CREATE TABLE SUPPLIER (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255)
);


CREATE TABLE PRODUCT(
    ID INT AUTO_INCREMENT,
    COLOR VARCHAR(255),
    SIZE VARCHAR(255),
	PRICE DECIMAL,
    SKU INT,
    AVAIL_QTY INT,
	CATEGORY_ID INT,
	SUPPLIER_ID INT
);
